# Site settings
exclude: [README.md,example1.md,example2.md]
title: Divya Appapogu
email: divsp@bu.edu
github: dspoorthy

description: > # this symbol means ignore newlines until "baseurl:"
    Hi! I'm Divya and here you will find what I do.
baseurl: "" # keep blank unless you're using sub-paths
url: "http://dspoorthy.github.io" # the base hostname & protocol for your site
#paginate: 3



# Build settings
markdown: kramdown

exclude: ['vendor']

